feat(#12): add floating action button with menu on profile screen
BinaryStudioAcademy/bsa-winter-2022-growup-mobile pull request #12
Opened 2022-02-10 14:31 UTC by R-Mielamud

2022-02-10 14:31 UTC, R-Mielamud commented
Looks like this:
<img width="228" alt="Знімок екрана 2022-02-10 о 16 29 12" src="https://user-images.githubusercontent.com/55893583/153428699-5d62f0c3-529e-41f2-863d-2c024a5430d7.png">

2022-02-10 16:51 UTC, AleksandrTermenzhy commented on package.json
> +    "react-native-floating-action": "^1.22.0",
I don't think we need extra library here. Please, take a look: https://callstack.github.io/react-native-paper/fab.html

2022-02-10 17:05 UTC, R-Mielamud commented on package.json
> +    "react-native-floating-action": "^1.22.0",
This library has a "magic" actions property, which creates a beautiful menu

2022-02-10 18:53 UTC, AleksandrTermenzhy commented on package.json
> +    "react-native-floating-action": "^1.22.0",
I'm not sure which magic you're talking about but check this out:
![IMG_20220210_205148](https://user-images.githubusercontent.com/80260839/153476659-1e232d9a-c736-4931-9546-4024378bd58a.jpg)

Isn't this a magic?)

2022-02-10 19:43 UTC, R-Mielamud commented on package.json
> +    "react-native-floating-action": "^1.22.0",
Fixed in 5b3ca09

2022-02-10 20:12 UTC, AleksandrTermenzhy approved these changes

2022-02-11 08:28 UTC, Liza-Veis requested changes

2022-02-11 08:28 UTC, Liza-Veis commented on src/screens/Profile/index.tsx
> +import React, { useState } from 'react';
Remove this file and move it's logic to profile.tsx, also rename Profile folder to lowercase

2022-02-11 08:28 UTC, Liza-Veis commented on src/screens/Profile/index.tsx
> +import addActions from './add-actions';
Add blank line after libraries imports

2022-02-11 08:28 UTC, Liza-Veis commented on src/screens/Profile/index.tsx
> +          onStateChange={({ open }) => setAddMenuOpen(open)}
let's put it in a separate callback like handleMenuStateChange

2022-02-11 08:28 UTC, Liza-Veis commented on src/screens/Profile/add-actions.tsx
> +const addActions = (select: (name: string) => void) => {
Change this file extension to .ts

2022-02-11 08:33 UTC, Liza-Veis commented
Now yarn.lock has missing dependencies, please reinstall dependencies and commit changes

2022-02-11 09:13 UTC, Liza-Veis commented on src/screens/profile/profile.tsx
> +    setAddMenuOpen(open);
```suggestion
  const handleMenuStateChange = ({ open }: { open: boolean }) => {
    setAddMenuOpen(open);
  }
```

2022-02-11 09:19 UTC, Liza-Veis approved these changes

2022-02-11 09:19 UTC, merged