#14 Setup redux
BinaryStudioAcademy/bsa-winter-2022-growup-mobile pull request #2
Opened 2022-02-07 18:06 UTC by jol79

2022-02-07 21:17 UTC, katyakostikova approved these changes

2022-02-08 12:55 UTC, Liza-Veis requested changes

2022-02-08 13:17 UTC, Liza-Veis commented
There are some changes that you need to do:
* you should use yarn for this project, so just remove package-lock.json and install dependencies via yarn
* now there are a lot of eslint errors, you have to fix them (if you are using vscode, you can install prettier extension)
* you should add .tsx extension only to files with components, all other files must be with .ts extension
* to make the app more scalable let's use the store structure from this [repo](https://github.com/BinaryStudioAcademy/bsa-winter-2022-growup/tree/develop/frontend/src), there is already auth slice, so you can follow it's logic
* you have to wrap App component in storeProvider and pass the store
* develop branch has changed, so you need to do rebase from it and resolve the conflicts

2022-02-08 15:18 UTC, jol79 commented
Based on the feedback:
- [ ] Use yarn for the project, remove _package-lock.json_ and install dependencies via yarn;
- [ ] Install prettier linter in vs code and refactor errors;
- [ ] Use **.ts** for the files that doesn't contain the component(s);
- [ ] Follow structure of the given repo;
- [ ] Wrap App component in **storeProvider** and pass the store;
- [ ] Rebase branch with last changes on the _develop_.

2022-02-08 22:17 UTC, AleksandrTermenzhy commented on package.json
> +    "all": "^0.0.0",
?

2022-02-08 22:17 UTC, AleksandrTermenzhy commented on src/screens/Login/index.tsx
> +import { useAppSelector, useAppDispatch } from '../../hooks/hooks';
Please add blank line to separate libraries imports and in-app

2022-02-08 22:17 UTC, AleksandrTermenzhy commented on src/screens/Login/index.tsx
> +    <Provider store={store}>
What for? You have already wrapped the whole app

2022-02-08 22:17 UTC, AleksandrTermenzhy commented on src/store/user/slice.ts
> +interface userState {
Let's agree interfaces the following way: `ISomeInterfaceName`

2022-02-09 10:25 UTC, Liza-Veis requested changes

2022-02-09 10:25 UTC, liza-veis commented on src/hooks/hooks.ts
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;
Move each hook to a separate file and re-export them from index.ts

2022-02-09 10:25 UTC, liza-veis commented on src/store/user/common.ts
> +  RemoveUser = 'removeUser',
```suggestion
  SIGN_IN = 'auth/sign-in',
```

2022-02-09 10:25 UTC, Liza-Veis commented on src/store/user/actions.ts
> +import { signIn, signOut } from './slice';
We don't need this import here, we won't use slice actions in thunks

2022-02-09 10:25 UTC, Liza-Veis commented on src/store/user/actions.ts
> +};
```suggestion
export  { signIn };
```

2022-02-09 10:25 UTC, Liza-Veis commented on src/store/user/actions.ts
> +);
```suggestion
const signIn = createAsyncThunk(
  ActionType.SIGN_IN,
  async (payload: ISignInPayload) => {
    // TODO: implement login logic
  }
);
```

2022-02-09 10:25 UTC, Liza-Veis commented on src/store/user/slice.ts
> +  isAdmin: boolean;
```suggestion
  user: IUser | null;
  isAuthorized: boolean;
```

2022-02-09 10:25 UTC, Liza-Veis commented on src/store/user/slice.ts
> +    },
We will use extraReducers and thunk actions for this
```suggestion
  reducers: {},
  extraReducers: builder => {
    builder.addCase(signIn.fulfilled, (state, { payload }) => {
      state.user = payload;
      state.isAuthorized = Boolean(payload);
    });
  },
```

2022-02-09 10:25 UTC, Liza-Veis commented on src/store/user/slice.ts
> +export const { reducer } = userSlice;
Import signIn from actions
```suggestion

const { reducer } = slice;

const actions = {
  ...slice.actions,
  signIn,
};

export { reducer, actions };
```

2022-02-09 10:25 UTC, Liza-Veis commented on src/store/user/slice.ts
> +export const userSlice = createSlice({
```suggestion
const slice = createSlice({
```

2022-02-09 10:25 UTC, Liza-Veis commented on src/store/user/slice.ts
> +  name: 'user',
Rename reducer name and user folder to auth

2022-02-09 14:35 UTC, katyakostikova approved these changes

2022-02-09 16:51 UTC, liza-veis requested changes

2022-02-09 16:51 UTC, Liza-Veis commented on src/App.tsx
> +import { store } from './store/store';
Let's rename store.ts to index.ts
```suggestion
import { store } from 'src/store';
```

2022-02-09 16:51 UTC, liza-veis commented on src/hooks/appDispatch.ts
> +import type { AppDispatch } from '../store/store';
We don't need to use "type" when we import types. Also we should name files in kebab case, so rename the file to use-app-dispatch.ts
```suggestion
import { useDispatch } from 'react-redux';

import { AppDispatch } from 'src/store';
```

2022-02-09 16:51 UTC, Liza-Veis commented on src/hooks/appSelector.ts
> +import type { RootState } from '../store/store';
Same here

2022-02-09 16:51 UTC, liza-veis commented on src/store/actions.ts
> +export { signIn } from './auth';
We should re-export here all the actions
```suggestion
export { authActions } from './auth';
```

2022-02-09 16:51 UTC, liza-veis commented on src/store/auth/index.ts
> +import { signIn } from './actions';
authActions already include signIn
```suggestion
import { reducer as authReducer, actions as authActions } from './slice';
```

2022-02-09 16:51 UTC, Liza-Veis commented on src/store/auth/slice.ts
> +interface IUserState {
```suggestion
interface IAuthState {
```

2022-02-09 16:51 UTC, liza-veis commented on src/store/auth/slice.ts
> +  name: 'user',
```suggestion
  name: 'auth',
```

2022-02-09 16:51 UTC, Liza-Veis commented on src/store/store.ts
> +export type AppDispatch = typeof store.dispatch;
Let's export from this file only store and move these types to types/app
-- app-dispatch.ts
-- root-state.ts
-- index.ts

2022-02-09 16:51 UTC, Liza-Veis commented on src/screens/Login/index.tsx
> +import { useAppSelector } from 'src/hooks';
```suggestion
import { useAppDispatch , useAppSelector } from 'src/hooks';
```

2022-02-09 16:51 UTC, Liza-Veis commented on src/screens/Login/index.tsx
> +  const isAuthorized = useAppSelector(state => state.auth.isAuthorized);
We will show the login screen only for unathorized users, the screen doesn't need to handle it, so remove this

2022-02-09 16:51 UTC, Liza-Veis commented on src/store/auth/actions.ts
> +
Add blank line after library import

2022-02-09 20:28 UTC, Liza-Veis approved these changes

2022-02-09 21:06 UTC, AleksandrTermenzhy approved these changes

2022-02-09 21:06 UTC, AleksandrTermenzhy commented on src/screens/Login/index.tsx
> +export { LoginScreen } from './login';
Login screen is out of this PR's scope. Please remove screen files before merge

2022-02-10 06:47 UTC, merged