New/gum 59 initial password setup
BinaryStudioAcademy/bsa-winter-2022-growup-mobile pull request #68
Opened 2022-03-30 09:49 UTC by jol79

2022-03-30 20:08 UTC, Liza-Veis requested changes

2022-03-30 20:08 UTC, liza-veis commented on src/screens/complete-registration/complete-registration.tsx
> +    </>
Wrap it in AuthScreen and remove styles.ts file as it done for RegisterScreen and LoginScreen

2022-03-30 20:08 UTC, liza-veis commented on src/screens/complete-registration/components/complete-registration-form/complete-registration-form.tsx
> +import { useAppDispatch, useAppNavigation } from 'src/hooks';
```suggestion
import { AuthRoute } from 'src/common/enums';
import { useAppDispatch, useAppNavigation } from 'src/hooks';
```

2022-03-30 20:08 UTC, liza-veis commented on src/screens/complete-registration/components/complete-registration-form/complete-registration-form.tsx
> +        });
Move all this logic to one action

2022-03-30 20:08 UTC, liza-veis commented on src/screens/complete-registration/components/complete-registration-form/complete-registration-form.tsx
> +              disabled={!isValid && accessToken !== undefined}
```suggestion
              disabled={!isValid && accessToken}
```

2022-03-30 20:08 UTC, Liza-Veis commented on src/services/http/index.ts
> +    if (accessToken !== null) {
```suggestion
    if (accessToken) {
```

2022-04-01 08:58 UTC, Liza-Veis requested changes

2022-04-01 08:58 UTC, Liza-Veis commented on android/app/src/main/AndroidManifest.xml
> +          <data android:scheme="@string/app_scheme" />
Remove changes that is not related to your pr

2022-04-01 08:58 UTC, Liza-Veis commented on src/components/auth-screen/auth-screen.tsx
> +  navigateScreen?: AuthRoute;
Don't make them optional

2022-04-01 08:58 UTC, Liza-Veis commented on src/services/auth-api/index.ts
> +    const authToken: { token: string } = await this.#http.load(
```suggestion
    const { token: accessToken }: { token: string } = await this.#http.load(
```

2022-04-01 08:58 UTC, Liza-Veis commented on src/services/http/index.ts
>        const token = await this.#storage.getItem(SecureStorageKey.ACCESS_TOKEN);
```suggestion
    if (hasAuth) {
      let token = accessToken;
      
      if (!token) {
        token = await this.#storage.getItem(SecureStorageKey.ACCESS_TOKEN);
      }
```

2022-04-01 08:58 UTC, Liza-Veis commented on src/services/auth-api/index.ts
> +        hasAuth: false,
```suggestion
```

2022-04-01 09:56 UTC, yevhenprybytok approved these changes

2022-04-01 09:57 UTC, Liza-Veis approved these changes

2022-04-01 09:59 UTC, merged