#2/Create User profile basic info layout
BinaryStudioAcademy/bsa-winter-2022-growup-mobile pull request #7
Opened 2022-02-09 14:24 UTC by Ihore4ik

2022-02-09 21:48 UTC, AleksandrTermenzhy commented on src/screens/Profile/components/userProfile/user_info.tsx
> +						  source={require("")}
?

2022-02-09 21:48 UTC, AleksandrTermenzhy commented on src/screens/Profile/components/userProfile/user_info.tsx
> +			<View style={{flexDirection: "row"}}>
Please, avoid inline styles.

2022-02-10 14:10 UTC, yevhenprybytok requested changes

2022-02-10 14:10 UTC, yevhenprybytok commented on src/screens/Profile/components/userProfile/user_info.tsx
> +import {StyleSheet, Text, View} from 'react-native';
```suggestion
import { StyleSheet, Text, View } from 'react-native';
```

2022-02-10 14:10 UTC, yevhenprybytok commented on src/screens/Profile/components/userProfile/user_info.tsx
> +							 icon="shield-check"/>
What happened to indentations?

2022-02-11 07:53 UTC, Liza-Veis commented
Please update you branch from develop and follow rest screens file structure

2022-02-11 08:54 UTC, liza-veis requested changes

2022-02-11 08:54 UTC, liza-veis commented on src/screens/Profile/components/user_info/styles.ts
> +import { StyleSheet } from 'react-native';
Add blank line after libraries imports

2022-02-11 08:54 UTC, Liza-Veis commented on src/screens/Profile/components/user_info/user_info.tsx
> +import { Text, View } from 'react-native';
Components file structure inside screens must be the same as in root components folder - create index.ts file and re-export this component, do the same in profile/components folder. Also rename Profile folder to lowercase, user_info to user-info

2022-02-11 08:54 UTC, liza-veis commented on src/screens/Profile/components/user_info/user_info.tsx
> +import { Subheading, Avatar, Headline, Colors } from 'react-native-paper';
Instead of these use our own Text component and don't use library colors - if you need additional color, add it to AppColor enum

2022-02-11 13:35 UTC, Liza-Veis commented
We already have profile folder (starts from lowercase), move components to it

2022-02-11 19:09 UTC, Liza-Veis requested changes

2022-02-11 19:09 UTC, Liza-Veis commented on src/screens/profile/components/user-info/user-info.tsx
> +      </Heading>
```suggestion
      <Heading level={HeadingLevel.H4}>
        Cristofer Westervelt
      </Heading>
```

2022-02-11 19:09 UTC, Liza-Veis commented on src/screens/profile/components/user-info/user-info.tsx
> +      </Heading>
```suggestion
      <Heading level={HeadingLevel.H6}>
        Fullstack JS Engineer
      </Heading>
```

2022-02-11 19:11 UTC, Liza-Veis commented
Please add margins between lines

![Screenshot 2022-02-11 at 21 06 11](https://user-images.githubusercontent.com/64521658/153654314-5be2eee8-31c6-4da4-ae68-759016ab6761.png)

2022-02-14 17:56 UTC, Liza-Veis requested changes

2022-02-14 17:56 UTC, Liza-Veis commented on src/screens/profile/components/user-info/user-info.tsx
> +        <Heading level={HeadingLevel.H6} style={styles.role}>
Here we have two options: use Heading and change font-family to 'NunitoSans-Regular' or use just text and set fontSize to 16. I would prefer the second one.
```suggestion
        <Text style={styles.role}>
```

2022-02-14 17:56 UTC, liza-veis commented on src/screens/profile/components/user-info/styles.ts
> +    position: 'relative',
```suggestion
```

2022-02-14 17:56 UTC, Liza-Veis commented on src/screens/profile/components/user-info/styles.ts
> +    fontWeight: '700',
```suggestion
```

2022-02-14 17:56 UTC, Liza-Veis commented on src/screens/profile/components/user-info/styles.ts
> +    fontFamily: 'NunitoSans',
```suggestion
    marginBottom: 8,
    fontSize: 16
```

2022-02-14 17:56 UTC, Liza-Veis commented on src/screens/profile/components/user-info/styles.ts
> +    bottom: 0,
It's better to avoid absolute
```suggestion
    alignItems: 'center',
```

2022-02-15 19:09 UTC, Liza-Veis requested changes

2022-02-15 19:09 UTC, Liza-Veis commented on src/screens/profile/components/user-info/styles.ts
> +const LEVEL_COLOR = '#5C5D5F';
Move it to app color

2022-02-15 21:29 UTC, AleksandrTermenzhy commented on src/screens/profile/components/user-info/styles.ts
> +    width: '100%',
`flex: 1` ?

2022-02-15 21:29 UTC, AleksandrTermenzhy commented on src/screens/profile/components/user-info/styles.ts
> +    left: -5,
Is there a real need of such styling?

2022-02-15 21:29 UTC, AleksandrTermenzhy commented on src/common/enums/ui/app-color.ts
> +  LEVEL_COLOR = '#5C5D5F',
There are multiple possible levels in the app. Such naming is misleading.

2022-02-15 21:29 UTC, AleksandrTermenzhy commented on src/screens/profile/components/user-info/user-info.tsx
> +        }}
Replace it with [user_profile](https://fonts.google.com/icons?selected=Material+Icons&icon.query=account_circle) icon.

2022-02-17 10:13 UTC, Liza-Veis requested changes

2022-02-17 10:13 UTC, Liza-Veis commented on src/screens/profile/components/user-info/user-info.tsx
> +      />
We can add it using just Icon. Don't forget to remove user_avatar.png 
```suggestion
    <Avatar.Icon size={152} icon="account" style={styles.avatar} />
```

2022-02-17 12:38 UTC, Liza-Veis approved these changes

2022-02-18 10:26 UTC, katyakostikova approved these changes

2022-02-21 16:21 UTC, AleksandrTermenzhy approved these changes

2022-02-21 16:21 UTC, AleksandrTermenzhy commented on src/screens/profile/components/user-info/user-info.tsx
> +const UserInfo = () => {
```suggestion
const UserInfo: React.FC = () => {
```

2022-02-21 16:21 UTC, AleksandrTermenzhy commented on src/screens/profile/components/user-info/styles.ts
> +    marginTop: 15,
It's better to handle margins on the usage-level and pass `cotainerStyle` prop to the component

2022-02-22 08:47 UTC, AleksandrTermenzhy approved these changes

2022-02-23 08:59 UTC, yevhenprybytok approved these changes

2022-02-23 09:45 UTC, merged