#24 Added theme, global components and styles
BinaryStudioAcademy/bsa-winter-2022-growup-mobile pull request #8
Opened 2022-02-09 14:27 UTC by katyakostikova

I'm not sure about styles of input, I've used TextInput from react-native-paper, but it has different view from inputs on Figma.

2022-02-09 17:45 UTC, Liza-Veis requested changes

2022-02-09 17:45 UTC, liza-veis commented on src/App.tsx
> +import theme from 'src/styles/theme/theme';
```suggestion
import theme from 'src/styles/theme';
```

2022-02-09 17:45 UTC, Liza-Veis commented on src/common/enums/button-type/button-type.ts
> +export { ButtonType };
Let's group button-type, heading-level, text-appearance, app-color and put ts files to one folder enums/ui

2022-02-09 17:45 UTC, liza-veis commented on src/common/enums/color/app-colors.ts
> +enum AppColors {
Enums should be singular

2022-02-09 17:45 UTC, Liza-Veis commented on src/components/button/styles.ts
> +  outlined: {
Use enum for keys here
```suggestion
  [ButtonType.OUTLINED]: {
```

2022-02-09 17:45 UTC, liza-veis commented on src/components/heading/styles.ts
> +  h4: {
```suggestion
  [HeadingLevel.H4]: {
```

2022-02-09 17:45 UTC, Liza-Veis commented on src/components/input/input.tsx
> +      value={field.name}
```suggestion
      ref={field.ref}
      value={field.value}
```

2022-02-09 17:45 UTC, Liza-Veis commented on src/components/input/input.tsx
> +      onChangeText={field.onChange}
```suggestion
      onChangeText={field.onChange}
      onBlur={field.onBlur}
```

2022-02-09 17:45 UTC, Liza-Veis commented on src/components/text/styles.ts
> +import { AppColors } from '../../common/enums';
```suggestion
import { AppColors } from 'src/common/enums';
```

2022-02-09 17:45 UTC, Liza-Veis commented on src/components/text/styles.ts
> +  hint: {
```suggestion
  [TextAppearance.HINT]: {
```

2022-02-09 17:45 UTC, Liza-Veis commented on src/components/text/text.tsx
> +import { TextAppearance } from '../../common/enums';
```suggestion
import { TextAppearance } from 'src/common/enums';
```

2022-02-09 17:45 UTC, Liza-Veis commented on src/styles/theme/theme.ts
> +import { AppColors } from '../../common/enums';
```suggestion
import { AppColors } from 'src/common/enums';
```

2022-02-09 17:45 UTC, Liza-Veis commented on src/styles/theme/index.ts
> +export * from './theme'
You can't re-export default in this way, same goes for all index.ts files in components
```suggestion
export { default } from './theme'
```

2022-02-09 17:47 UTC, Liza-Veis commented
Please add blank line after libraries imports

2022-02-09 21:46 UTC, AleksandrTermenzhy requested changes

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/button/styles.ts
> +    borderRadius: 20,
You can move it to theme as `roundness`

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/button/button.tsx
> +};
Let's stick to existing naming and just passthrough props which we don't need to use.

`color={AppColor.ACCENT}` -- why using the same color for all variants?

```suggestion
const Button: React.FC<IButtonProps> = ({ children, mode, ...buttonProps }) => {
  return (
    <ButtonPaper
      uppercase={false}
      style={{ ...styles.global, ...styles[mode] }}
      mode={mode}
      color={AppColor.ACCENT}
      {...buttonProps}
    >
      {children}
    </ButtonPaper>
  );
};
```

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/button/styles.ts
> +  [ButtonType.CONTAINED]: {},
No use -- no code

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/button/button.tsx
> +};
```suggestion
type ButtonProps = React.ComponentPropsWithoutRef<typeof ButtonPaper> & {
   // specific props go here, if any
};
```

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/heading/heading.tsx
> +};
```suggestion
type HeadingProps = React.ComponentPropsWithoutRef<typeof Text> {
  level: HeadingLevel;
};
```

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/heading/heading.tsx
> +  return <Text style={{ ...styles[level], ...style }}>{children}</Text>;
```suggestion
  return <Text style={[styles[level], style]}>{children}</Text>;
```

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/heading/heading.tsx
> +const Heading: React.FC<IHeadingProps> = ({ children, level, style }) => {
We should set some default value for `level` here to avoid reaching `style[undefined]`

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/input/input.tsx
> +type IInputProps = {
The same here... Just extend it from default TextInput props

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/components/input/input.tsx
> +  const { field } = useController({ name, control });
I don't think it is a good idea to keep hooks in common components. We might want to use this component without any form-handler.

Only styles should be applied here. The rest we can always pass with existing props

2022-02-09 21:46 UTC, AleksandrTermenzhy commented on src/styles/fonts/font-config.ts
> +  android: {
Let's set it up for all platforms

2022-02-09 22:17 UTC, katyakostikova commented on src/components/button/button.tsx
> +};
Same color because it sets this color to background or text color depending on button mode. If the problem is that we can't pass another color, I'll change it

2022-02-10 13:03 UTC, AleksandrTermenzhy approved these changes

2022-02-10 13:18 UTC, yevhenprybytok approved these changes

2022-02-10 13:19 UTC, Liza-Veis commented on src/common/enums/ui/button-mode/button-mode.ts
> +enum ButtonMode {
We don't need to put these files in separate folders. Let's keep other enums file structure:
 ui 
 --button-mode.ts
 --button-type.ts

2022-02-10 13:43 UTC, Liza-Veis approved these changes

2022-02-10 13:43 UTC, merged